/*
 * Created on 2019-12-26 ( Time 13:27:37 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package dizertatie.be.dizertatie.domain.repository;

import dizertatie.be.dizertatie.domain.bean.Challenge;
import dizertatie.be.dizertatie.domain.bean.ChallengeAttempt;
import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;

import java.awt.print.Pageable;
import java.util.List;

/**
 * Spring JPA Repository for OriLogs
 * 
 * @author Telosys Tools Generator
 *
 */
@Repository
public interface ChallengeAttemptRepository extends CrudRepository<ChallengeAttempt, Long> {
    ChallengeAttempt findFirstByAccount_IdAndChallenge_IdAndIdNotOrderByScoreDesc(Long accountId, Long challengeId, Long currentChallengeAttemptId);
    List<ChallengeAttempt> findByAccount_Username(String userName);
    List<ChallengeAttempt> findByAccount_UsernameAndChallenge_IdOrderByCreatedAtDesc(String userName, Long id);
}