/*
 * Created on 2019-12-26 ( Time 13:27:38 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package dizertatie.be.dizertatie.domain.service;

//import io.swagger.models.auth.In;

import dizertatie.be.dizertatie.domain.bean.AccountXCourse;
import dizertatie.be.dizertatie.domain.repository.AccountXCourseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional
public class AccountXCourseDomainService {

    @Autowired
    private AccountXCourseRepository accountXCourseRepository;


    public AccountXCourse findById(Long id) {
        return accountXCourseRepository.findById(id).isPresent() ? accountXCourseRepository.findById(id).get() : null;
    }

    public List<AccountXCourse> findAll() {
        return (List<AccountXCourse>) accountXCourseRepository.findAll();
    }

    public long countAll() {
        return accountXCourseRepository.count();
    }

    public AccountXCourse save(AccountXCourse record) {
        AccountXCourse saved = accountXCourseRepository.save(record);
        return saved;
    }
}