/*
 * Created on 2019-12-26 ( Time 13:27:38 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package dizertatie.be.dizertatie.domain.service;

//import io.swagger.models.auth.In;

import dizertatie.be.dizertatie.domain.bean.Account;
import dizertatie.be.dizertatie.domain.bean.Challenge;
import dizertatie.be.dizertatie.domain.repository.AccountRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional
public class AccountDomainService {

    @Autowired
    private AccountRepository accountRepository;


    public Account findByUserNameAndPassword(String username, String password) {
        return accountRepository.findByUsernameAndPassword(username, password);
    }

    public Account findByUsername(String username) {
        return accountRepository.findByUsername(username);
    }

    public Account findById(Long id) {
        return accountRepository.findById(id).isPresent() ? accountRepository.findById(id).get() : null;
    }

    public List<Account> findAll() {
        return (List<Account>) accountRepository.findAll();
    }

    public long countAll() {
        return accountRepository.count();
    }

    public Account save(Account record) {
        Account saved = accountRepository.save(record);
        return saved;
    }
}