/*
 * Created on 2019-12-26 ( Time 13:27:38 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package dizertatie.be.dizertatie.domain.service;
import dizertatie.be.dizertatie.domain.bean.ChallengeItem;
import dizertatie.be.dizertatie.domain.repository.ChallengeItemRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional
public class ChallengeItemDomainService {

    @Autowired
    private ChallengeItemRepository challengeItemRepository;


    public ChallengeItem findById(Long id) {
        return challengeItemRepository.findById(id).isPresent() ? challengeItemRepository.findById(id).get() : null;
    }

    public List<ChallengeItem> findAll() {
        return (List<ChallengeItem>) challengeItemRepository.findAll();
    }

    public long countAll() {
        return challengeItemRepository.count();
    }

    public ChallengeItem create(ChallengeItem record) {
        ChallengeItem saved = challengeItemRepository.save(record);
        return saved;
    }

}