/*
 * Created on 2019-12-26 ( Time 13:27:38 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package dizertatie.be.dizertatie.domain.service;

//import io.swagger.models.auth.In;

import dizertatie.be.dizertatie.domain.bean.Challenge;
import dizertatie.be.dizertatie.domain.repository.ChallengeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

@Service
@Transactional
public class ChallengeDomainService {

    @Autowired
    private ChallengeRepository challengeRepository;


    public Challenge findById(Long id) {
        return challengeRepository.findById(id).isPresent() ? challengeRepository.findById(id).get() : null;
    }

    public List<Challenge> findAll() {
        return (List<Challenge>) challengeRepository.findAll();
    }

    public long countAll() {
        return challengeRepository.count();
    }

    public Challenge save(Challenge record) {
        Challenge saved = challengeRepository.save(record);
        return saved;
    }

    public Challenge create(Challenge record) {
        Challenge saved = challengeRepository.save(record);
        return saved;
    }

}