/*
 * Created on 2019-12-26 ( Time 13:27:38 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package dizertatie.be.dizertatie.domain.service;

//import io.swagger.models.auth.In;

import dizertatie.be.dizertatie.domain.bean.Course;
import dizertatie.be.dizertatie.domain.repository.CourseRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional
public class CourseDomainService {

    @Autowired
    private CourseRepository courseRepository;

    public Course findById(Long id) {
        return courseRepository.findById(id).isPresent() ? courseRepository.findById(id).get() : null;
    }

    public List<Course> findByStudentUsername(String username) {
        //return courseRepository.findByAccount_Username(username);
        return null;
    }

    public List<Course> findByTeacherUsername(String username) {
       // return courseRepository.findByAccount_Username(username);
        return null;
    }

    public List<Course> findNotEnrolledCourse(long accountId){
        return courseRepository.findNotEnrolledCourses(accountId);
    }

    public List<Course> findAll() {
        return (List<Course>) courseRepository.findAll();
    }

    public long countAll() {
        return courseRepository.count();
    }

    public Course save(Course record) {
        Course saved = courseRepository.save(record);
        return saved;
    }
}