/*
 * Created on 2019-12-26 ( Time 13:27:38 )
 * Generated by Telosys Tools Generator ( version 3.0.0 )
 */

package dizertatie.be.dizertatie.domain.service;

//import io.swagger.models.auth.In;

import dizertatie.be.dizertatie.domain.bean.Lesson;
import dizertatie.be.dizertatie.domain.repository.LessonRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@Transactional
public class LessonDomainService {

    @Autowired
    private LessonRepository lessonRepository;

    public Lesson findById(Long id) {
        return lessonRepository.findById(id).isPresent() ? lessonRepository.findById(id).get() : null;
    }

    public List<Lesson> findAll() {
        return (List<Lesson>) lessonRepository.findAll();
    }

    public long countAll() {
        return lessonRepository.count();
    }

    public Lesson save(Lesson record) {
        Lesson saved = lessonRepository.save(record);
        return saved;
    }
}